/* Desktop/mobile journal workflow using genuine disposable WordPress cookies. */
'use strict';
const fs = require('node:fs');
const assert = require('node:assert/strict');
const { chromium } = require(process.env.TGIT_PLAYWRIGHT_MODULE || './browser/node_modules/playwright-core');
const runId = Date.now();
const strategyName = 'Browser fixture strategy ' + runId;
const tradeName = 'Browser multi-image journal ' + runId;
const fixture = JSON.parse(fs.readFileSync('tmp/journal-http-fixtures.json', 'utf8'));
(async () => {
 const browser = await chromium.launch({ executablePath: process.env.TGIT_CHROME_EXECUTABLE || 'C:/Program Files/Google/Chrome/Application/chrome.exe', headless: true });
 try {
  const context = await browser.newContext({ viewport: { width: 1100, height: 900 } }); const session = fixture.sessions.owner;
  await context.addCookies([{ name: session.cookie_name, value: session.cookie_value, url: 'http://127.0.0.1:19308', httpOnly: true }]);
  const page = await context.newPage(); page.setDefaultTimeout(60000); const errors = []; page.on('pageerror', (error) => errors.push(error.message));
  await page.goto('http://127.0.0.1:19308/preview'); await page.locator('#tgit-workspace').selectOption(String(fixture.workspace));
  await page.locator('#tgit-content').waitFor({ state: 'visible' });
  if (await page.locator('.tgit-menu-toggle').isVisible() && await page.locator('.tgit-menu-toggle').getAttribute('aria-expanded') === 'false') await page.locator('.tgit-menu-toggle').click();
  await page.getByRole('tab', { name: 'Strategies', exact: true }).click();
  await page.locator('#tgit-strategies').getByText('Fixture strategy', { exact: true }).waitFor();
  console.log('CHECK Journal workspace loaded.');
  await page.locator('#tgit-strategy-form input[name=name]').fill(strategyName);
  await page.locator('#tgit-strategy-form textarea[name=description]').fill('<p>Plan captured before entry</p>');
  await page.locator('#tgit-strategy-form textarea[name=rules]').fill('<strong>Manual checklist</strong>');
  await page.locator('#tgit-strategy-form textarea[name=tags]').fill('browser\nfixture');
  await page.locator('#tgit-strategy-form button[type=submit]').click();
  await page.locator('#tgit-strategies').getByText(strategyName, { exact: true }).waitFor();
  console.log('CHECK Strategy created.');
  await page.locator('#tgit-content').waitFor({ state: 'visible' });
  if (await page.locator('.tgit-menu-toggle').isVisible() && await page.locator('.tgit-menu-toggle').getAttribute('aria-expanded') === 'false') await page.locator('.tgit-menu-toggle').click();
  await page.getByRole('tab', { name: 'Trade Journal', exact: true }).click();
  await page.locator('#tgit-new-trade').click();
  const form = page.locator('#tgit-trade-form'); await form.locator('input[name=title]').fill(tradeName);
  await form.locator('textarea[name=thesis]').fill('<strong>Independent journal idea</strong>');
  await form.locator('textarea[name=notes]').fill('Feeling calm; no financial effect.');
  await form.locator('textarea[name=confluences]').fill('Manual level\nVolume context');
  await page.locator('#tgit-confluence-items input').nth(0).check();
  await form.locator('input[name=planned_stop]').fill('0.123456789012345678');
  const versions = await form.locator('select[name=strategy_version_id] option').allTextContents(); const chosen = versions.find((value) => value.includes(strategyName));
  await form.locator('select[name=strategy_version_id]').selectOption({ label: chosen });
  const buffer = fs.readFileSync(fixture.fixture); await form.locator('input[name=images]').setInputFiles(['one', 'two', 'three'].map((name) => ({ name: `UI-${name}.png`, mimeType: 'image/png', buffer })));
  await form.locator('button[type=submit]').click();
  await page.locator('#tgit-journal-status').getByText('Saved.', { exact: true }).waitFor();
  assert.equal(await page.locator('#tgit-gallery article').count(), 3); console.log('CHECK Three-image gallery ready.');
  await page.waitForFunction(() => [...document.querySelectorAll('#tgit-gallery img')].every((image) => image.naturalWidth > 0 && image.src.startsWith('blob:')));
  const first = page.locator('#tgit-gallery article').filter({ has: page.getByText('UI-one.png', { exact: true }) });
  await first.locator('input[name=caption]').fill('Entry chart caption'); await first.locator('input[name=alt_text]').fill('Blue entry chart fixture'); await first.locator('input[name=sort_order]').fill('22'); await first.locator('select[name=stage]').selectOption('entry');
  await first.getByRole('button', { name: 'Save image details' }).click(); await page.locator('#tgit-gallery').getByText('Entry chart caption', { exact: true }).waitFor(); assert.equal(await first.locator('select[name=stage]').inputValue(), 'entry');
  await first.getByRole('button', { name: 'Remove image (recoverable)', exact: true }).click(); await first.getByRole('button', { name: 'Restore image', exact: true }).waitFor();
  await first.getByRole('button', { name: 'Restore image', exact: true }).click(); await first.getByRole('button', { name: 'View original', exact: true }).waitFor();
  await page.locator('#tgit-gallery input[type=checkbox]').nth(0).check(); await page.locator('#tgit-gallery input[type=checkbox]').nth(1).check();
  await page.locator('#tgit-compare-images').click(); await page.waitForFunction(() => document.querySelectorAll('#tgit-image-view img').length === 2 && [...document.querySelectorAll('#tgit-image-view img')].every((image) => image.naturalWidth > 0));
  await page.screenshot({ path: 'tmp/journal-desktop.png', fullPage: true }); await page.locator('#tgit-close-image').click();
  await page.setViewportSize({ width: 360, height: 800 }); await page.locator('#tgit-trade-detail').scrollIntoViewIfNeeded();
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth), true, 'Mobile page overflows horizontally.');
  await page.screenshot({ path: 'tmp/journal-mobile.png', fullPage: true });
  await page.locator('#tgit-close-trade').click();
  const journalCard = page.locator('#tgit-trades article').filter({ has: page.getByText(tradeName, { exact: true }) }); await journalCard.getByRole('button', { name: 'Open journal' }).click();
  assert.equal(await form.locator('textarea[name=notes]').inputValue(), 'Feeling calm; no financial effect.');
  assert.equal(await form.locator('input[name=planned_stop]').inputValue(), '0.123456789012345678');
  assert.equal(await page.locator('#tgit-confluence-items input').nth(0).isChecked(), true); assert.equal(await page.locator('#tgit-confluence-items input').nth(1).isChecked(), false);
  assert.equal(await page.locator('#tgit-gallery article').count(), 3); assert.equal(await page.locator('#tgit-gallery article').filter({ has: page.getByText('UI-one.png', { exact: true }) }).locator('select[name=stage]').inputValue(), 'entry'); assert.deepEqual(errors, []);
  console.log('PASS Desktop/mobile journal: strategy snapshot, exact fields, three uploads, captions/order, delete/restore, comparison and reopening; no JavaScript errors or horizontal mobile overflow.');
 } finally { await browser.close(); }
})().catch((error) => { console.error(error.message); process.exitCode = 1; });
