/* Desktop/mobile journal workflow using genuine disposable WordPress cookies. */
'use strict';
const fs = require('node:fs');
const assert = require('node:assert/strict');
const { chromium } = require(process.env.TGIT_PLAYWRIGHT_MODULE || './browser/node_modules/playwright-core');
const runId = Date.now();
const strategyName = 'Browser fixture strategy ' + runId;
const tradeName = 'Browser multi-image journal ' + runId;
const fixture = JSON.parse(fs.readFileSync('tmp/journal-http-fixtures.json', 'utf8'));
(async () => {
 const browser = await chromium.launch({ executablePath: process.env.TGIT_CHROME_EXECUTABLE || 'C:/Program Files/Google/Chrome/Application/chrome.exe', headless: true });
 try {
  const context = await browser.newContext({ viewport: { width: 1100, height: 900 } }); const session = fixture.sessions.owner;
  await context.addCookies([{ name: session.cookie_name, value: session.cookie_value, url: 'http://127.0.0.1:19308', httpOnly: true }]);
  const page = await context.newPage(); page.setDefaultTimeout(60000); const errors = []; page.on('pageerror', (error) => errors.push(error.message));
  await page.goto('http://127.0.0.1:19308/preview'); await page.locator('#tgit-workspace').selectOption(String(fixture.workspace));
  await page.locator('#tgit-content').waitFor({ state: 'visible' });
  if (await page.locator('.tgit-menu-toggle').isVisible() && await page.locator('.tgit-menu-toggle').getAttribute('aria-expanded') === 'false') await page.locator('.tgit-menu-toggle').click();
  await page.getByRole('tab', { name: 'Strategies', exact: true }).click();
  await page.locator('#tgit-strategies').getByText('Fixture strategy', { exact: true }).waitFor();
  console.log('CHECK Journal workspace loaded.');
  await page.locator('#tgit-new-strategy').click();
  await page.locator('#tgit-strategy-form input[name=name]').fill(strategyName);
  await page.locator('#tgit-strategy-form textarea[name=description]').fill('<p>Plan captured before entry</p>');
  await page.locator('#tgit-strategy-form textarea[name=rules]').fill('<strong>Manual checklist</strong>');
  for (const tag of ['browser', 'fixture']) { await page.locator('#tgit-strategy-form').getByRole('textbox', { name: 'New tag', exact: true }).fill(tag); await page.locator('#tgit-strategy-form').getByRole('textbox', { name: 'New tag', exact: true }).press('Enter'); }
  await page.locator('#tgit-strategy-form button[type=submit]').click();
  await page.locator('#tgit-strategies').getByText(strategyName, { exact: true }).waitFor();
  console.log('CHECK Strategy created.');
  await page.locator('#tgit-content').waitFor({ state: 'visible' });
  if (await page.locator('.tgit-menu-toggle').isVisible() && await page.locator('.tgit-menu-toggle').getAttribute('aria-expanded') === 'false') await page.locator('.tgit-menu-toggle').click();
  await page.getByRole('tab', { name: 'Trade Journal', exact: true }).click();
  await page.locator('#tgit-new-trade').click();
  const form = page.locator('#tgit-trade-form'); await form.locator('input[name=title]').fill(tradeName);
  await page.locator('#tgit-save-journal').click(); await page.locator('#tgit-journal-status').getByText('Saved.', { exact: true }).waitFor();
  const fillFixtures = await page.evaluate(async () => {
   const route = new URL(location.href), base = `workspaces/${route.searchParams.get('tgit_workspace')}`;
   const post = async (target, body) => { const response = await fetch(tgitRestUrl(tgitConfig.root, `${base}/${target}`), { method: 'POST', headers: { 'X-WP-Nonce': tgitConfig.nonce, 'Idempotency-Key': crypto.randomUUID(), 'Content-Type': 'application/json' }, body: JSON.stringify(body) }); if (!response.ok) throw new Error((await response.json()).message); return (await response.json()).data; };
   const asset = Number(document.querySelector('#tgit-trade-form [name=asset_id]').value), account = Number(document.querySelector('#tgit-transaction-form [name=account_id]').value);
   const input = { account_id: account, asset_id: asset, action: 'buy', state: 'draft', effective_date: '2026-01-04', quantity: '1.123456789012345678', unit_price: '12', fees: '0.25', currency: 'USD' };
   const draft = (await post('transactions', input)).transaction, posted = (await post('transactions', { ...input, state: 'posted', quantity: '1' })).transaction, assigned = (await post('transactions', input)).transaction;
   await post('trades', { asset_id: asset, title: 'Assigned picker fixture', state: 'planned', transaction_ids: [Number(assigned.id)], journal: {} });
   const accounts = (await (await fetch(tgitRestUrl(tgitConfig.root, `${base}/accounts`), { headers: { 'X-WP-Nonce': tgitConfig.nonce } })).json()).data;
   return { draft: String(draft.id), posted: String(posted.id), assigned: String(assigned.id), accounts };
  });
  await page.locator('#tgit-detail-tab-transactions').click(); await page.locator('#tgit-link-transactions').click();
  await page.locator('#tgit-fill-picker').getByRole('searchbox', { name: 'Search Eligible transactions', exact: true }).waitFor(); await page.waitForFunction(() => !window.tgitWriteBusy);
  assert.equal(await page.locator('#tgit-fill-picker').getByRole('checkbox', { name: `Link transaction ${fillFixtures.assigned}`, exact: true }).count(), 0);
  await page.locator('#tgit-fill-picker').getByRole('checkbox', { name: `Link transaction ${fillFixtures.draft}`, exact: true }).check();
  await page.locator('#tgit-fill-picker').getByRole('checkbox', { name: `Link transaction ${fillFixtures.posted}`, exact: true }).check();
  assert((await page.locator('#tgit-fill-facts').textContent()).includes('1.123456789012345678'));
  await page.getByLabel('Transaction state', { exact: true }).selectOption('posted'); assert.equal(await page.locator('#tgit-fill-picker').getByRole('checkbox', { name: `Link transaction ${fillFixtures.draft}`, exact: true }).count(), 0);
  await page.locator('#tgit-save-journal').click(); await page.locator('#tgit-journal-status').getByText('Saved.', { exact: true }).waitFor();
  const cashAfterLinks = await page.evaluate(async () => { const route = new URL(location.href); return (await (await fetch(tgitRestUrl(tgitConfig.root, `workspaces/${route.searchParams.get('tgit_workspace')}/accounts`), { headers: { 'X-WP-Nonce': tgitConfig.nonce } })).json()).data; }); assert.deepEqual(cashAfterLinks, fillFixtures.accounts);
  await page.locator('#tgit-detail-tab-transactions').click(); assert.equal(await page.locator('#tgit-fill-facts tbody tr').count(), 2);
  await page.locator('#tgit-fill-facts tbody tr').filter({ has: page.getByText(`#${fillFixtures.draft}`, { exact: true }) }).getByRole('button', { name: 'Remove link', exact: true }).click();
  const rejectLinks = (dialog) => dialog.dismiss(); page.on('dialog', rejectLinks); await page.locator('#tgit-close-trade').click(); assert.equal(await page.locator('#tgit-trade-detail').isVisible(), true); page.off('dialog', rejectLinks);
  await page.locator('#tgit-save-journal').click(); await page.locator('#tgit-journal-status').getByText('Saved.', { exact: true }).waitFor();
  await page.locator('#tgit-detail-tab-transactions').click(); assert.equal(await page.locator('#tgit-fill-facts tbody tr').count(), 1);
  console.log('CHECK Transaction picker selection, state filter, unlink revision and unchanged cash.');
  await page.getByRole('tab', { name: 'Plan and journal', exact: true }).click();
  assert.equal(await form.locator('.tgit-journal-group').count(), 5);
  await page.screenshot({ path: 'tmp/journal-plan-desktop.png', fullPage: true });
  await page.setViewportSize({ width: 360, height: 800 });
  assert(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth));
  await page.screenshot({ path: 'tmp/journal-plan-mobile.png', fullPage: true }); await page.setViewportSize({ width: 1100, height: 900 });
  await form.locator('textarea[name=thesis]').fill('<strong>Independent journal idea</strong>');
  await form.locator('textarea[name=notes]').fill('Feeling calm; no financial effect.');
  await page.getByRole('textbox', { name: 'New confluence', exact: true }).fill('Manual level'); await page.getByRole('textbox', { name: 'New confluence', exact: true }).press('Enter');
  await page.getByRole('textbox', { name: 'New confluence', exact: true }).fill('Volume context'); await page.getByRole('button', { name: 'Add confluence', exact: true }).click();
  await page.getByRole('textbox', { name: 'New tag', exact: true }).fill('Café review'); await page.getByRole('textbox', { name: 'New tag', exact: true }).press('Enter');
  await page.getByRole('textbox', { name: 'New tag', exact: true }).fill('Café review'); await page.getByRole('button', { name: 'Add tag', exact: true }).click(); await page.locator('#tgit-journal-status').getByText('This tag already exists.', { exact: true }).waitFor();
  await page.getByRole('textbox', { name: 'New tag', exact: true }).fill('temporary'); await page.getByRole('button', { name: 'Add tag', exact: true }).click(); await page.getByRole('button', { name: 'Remove tag temporary', exact: true }).click();
  await page.getByRole('textbox', { name: 'New tag', exact: true }).fill('é'.repeat(100)); await page.getByRole('button', { name: 'Add tag', exact: true }).click(); await page.locator('#tgit-journal-status').getByText('Enter a tag of up to 190 UTF-8 bytes on one line.', { exact: true }).waitFor(); await page.getByRole('textbox', { name: 'New tag', exact: true }).fill('');
  await page.locator('#tgit-confluence-items input').nth(0).check();
  await page.getByRole('textbox', { name: 'New confluence', exact: true }).fill('Temporary check'); await page.getByRole('button', { name: 'Add confluence', exact: true }).click(); await page.getByRole('button', { name: 'Remove confluence Temporary check', exact: true }).click(); assert.equal(await page.locator('#tgit-confluence-items input').nth(0).isChecked(), true);
  await form.locator('input[name=planned_stop]').fill('0.123456789012345678');
  const versions = await form.locator('select[name=strategy_version_id] option').allTextContents(); const chosen = versions.find((value) => value.includes(strategyName));
  await form.locator('select[name=strategy_version_id]').selectOption({ label: chosen });
  await page.locator('#tgit-save-journal').click();
  await page.locator('#tgit-journal-status').getByText('Saved.', { exact: true }).waitFor();
  await page.getByRole('tab', { name: 'History', exact: true }).click(); assert((await page.locator('#tgit-trade-history h3').textContent()).startsWith('Journal revisions ('));
  const latestRevision = page.locator('#tgit-trade-history tbody tr').first(); assert(!(await latestRevision.locator('[data-label=Author]').textContent()).includes('undefined'));
  await latestRevision.getByRole('button', { name: 'View revision', exact: true }).click(); await page.locator('#tgit-revision-detail dd').filter({ hasText: 'Café review' }).waitFor();
  await page.locator('#tgit-revision-detail').getByRole('button', { name: 'Close revision', exact: true }).click(); assert.equal(await page.locator('#tgit-revision-detail').isVisible(), false);
  await page.getByRole('tab', { name: 'Images', exact: true }).click();
  const journalRevision = () => page.evaluate(async () => {
   const route = new URL(location.href), target = `workspaces/${route.searchParams.get('tgit_workspace')}/trades/${route.searchParams.get('tgit_trade')}`;
   return (await (await fetch(tgitRestUrl(tgitConfig.root, target), { headers: { 'X-WP-Nonce': tgitConfig.nonce } })).json()).data.trade.revision;
  }); const beforeImageUpload = await journalRevision();
  const buffer = fs.readFileSync(fixture.fixture); await page.locator('input[name=images]').setInputFiles(['one', 'two', 'three'].map((name) => ({ name: `UI-${name}.png`, mimeType: 'image/png', buffer })));
  await page.locator('#tgit-upload-images').click(); await page.locator('#tgit-journal-status').getByText('Images uploaded.', { exact: true }).waitFor().catch(async (error) => { throw new Error(error.message + ' Status: ' + await page.locator('#tgit-journal-status').textContent()); });
  assert.equal(await page.locator('#tgit-gallery tbody tr').count(), 3); console.log('CHECK Three-image gallery ready.');
  assert.equal(await journalRevision(), beforeImageUpload, 'Image uploads must not create a journal revision.');
  await page.waitForFunction(() => [...document.querySelectorAll('#tgit-gallery img')].every((image) => image.naturalWidth > 0 && image.src.startsWith('blob:')));
  console.log('CHECK Private thumbnails decoded.');
  const first = page.locator('#tgit-gallery tbody tr').filter({ has: page.getByText('UI-one.png', { exact: true }) });
  await first.getByRole('button', { name: 'Edit details', exact: true }).click();
  const editor = page.locator('#tgit-image-editor');
  await editor.locator('input[name=caption]').fill('Entry chart caption'); await editor.locator('input[name=alt_text]').fill('Blue entry chart fixture'); await editor.locator('input[name=sort_order]').fill('22'); await editor.locator('select[name=stage]').selectOption('entry');
  await editor.getByRole('button', { name: 'Save image details' }).click(); await page.locator('#tgit-gallery').getByText('Entry chart caption', { exact: true }).waitFor(); assert.equal(await first.locator('[data-label=Stage]').textContent(), 'entry');
  await page.getByRole('searchbox', { name: 'Search Images', exact: true }).fill('UI-one'); assert.equal(await page.locator('#tgit-gallery tbody tr').count(), 1);
  await first.getByRole('button', { name: 'Edit details', exact: true }).click(); await editor.locator('input[name=caption]').fill('Unsaved image caption');
  const rejectImageDiscard = (dialog) => dialog.dismiss(); page.on('dialog', rejectImageDiscard); await editor.getByRole('button', { name: 'Cancel image details', exact: true }).click(); assert.equal(await editor.isVisible(), true);
  await page.locator('#tgit-close-trade').click(); assert.equal(await page.locator('#tgit-trade-detail').isVisible(), true); page.off('dialog', rejectImageDiscard);
  page.once('dialog', (dialog) => dialog.accept()); await editor.getByRole('button', { name: 'Cancel image details', exact: true }).click(); assert.equal(await editor.isVisible(), false);
  assert.equal(await page.getByRole('searchbox', { name: 'Search Images', exact: true }).inputValue(), 'UI-one');
  await page.locator('#tgit-gallery').getByRole('button', { name: 'Clear search', exact: true }).click();
  await first.getByRole('button', { name: 'Edit details', exact: true }).click();
  const imageConflictStatus = await page.evaluate(async () => {
   const route = new URL(location.href), base = `workspaces/${route.searchParams.get('tgit_workspace')}`;
   const gallery = (await (await fetch(tgitRestUrl(tgitConfig.root, `${base}/trades/${route.searchParams.get('tgit_trade')}/images`), { headers: { 'X-WP-Nonce': tgitConfig.nonce } })).json()).data;
   const row = gallery.items.find((image) => image.filename === 'UI-one.png');
   return (await fetch(tgitRestUrl(tgitConfig.root, `${base}/images/${row.id}/metadata`), { method: 'POST', headers: { 'X-WP-Nonce': tgitConfig.nonce, 'Idempotency-Key': crypto.randomUUID(), 'Content-Type': 'application/json' }, body: JSON.stringify({ caption: row.caption, alt_text: 'Concurrent image description', timeframe: row.timeframe, stage: row.stage, sort_order: Number(row.sort_order), expected_revision: Number(row.revision) }) })).status;
  }); assert.equal(imageConflictStatus, 200);
  await editor.locator('input[name=caption]').fill('Retained image conflict draft'); await editor.getByRole('button', { name: 'Save image details', exact: true }).click();
  await page.waitForFunction(() => !window.tgitWriteBusy); assert.equal(await editor.locator('input[name=caption]').inputValue(), 'Retained image conflict draft');
  page.once('dialog', (dialog) => dialog.accept()); await editor.getByRole('button', { name: 'Reload latest image details', exact: true }).click();
  await page.waitForFunction(() => !window.tgitWriteBusy); assert.equal(await editor.locator('input[name=alt_text]').inputValue(), 'Concurrent image description');
  await editor.getByRole('button', { name: 'Cancel image details', exact: true }).click();
  await first.getByRole('button', { name: 'Move to Trash', exact: true }).click(); await page.getByLabel('Image view', { exact: true }).selectOption('trash'); await first.getByRole('button', { name: 'Restore image', exact: true }).waitFor();
  await first.getByRole('button', { name: 'Restore image', exact: true }).click(); await page.getByLabel('Image view', { exact: true }).selectOption('active'); await first.getByRole('button', { name: 'View original', exact: true }).waitFor();
  await page.locator('#tgit-gallery tbody input[type=checkbox]').nth(0).check(); await page.locator('#tgit-gallery tbody input[type=checkbox]').nth(1).check();
  await page.locator('#tgit-compare-images').click(); await page.waitForFunction(() => document.querySelectorAll('#tgit-image-view img').length === 2 && [...document.querySelectorAll('#tgit-image-view img')].every((image) => image.naturalWidth > 0));
  await page.screenshot({ path: 'tmp/journal-desktop.png', fullPage: true }); await page.locator('#tgit-close-image').click();
  await page.setViewportSize({ width: 360, height: 800 }); await page.locator('#tgit-trade-detail').scrollIntoViewIfNeeded();
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth), true, 'Mobile page overflows horizontally.');
  assert(await page.locator('#tgit-gallery tbody tr').evaluateAll((rows) => rows.every((row) => row.getBoundingClientRect().height < 200)), 'Ready image rows should remain compact at mobile width.');
  await page.screenshot({ path: 'tmp/journal-mobile.png', fullPage: true });
  await page.locator('#tgit-close-trade').click();
  await page.getByRole('searchbox', { name: 'Search Trades', exact: true }).fill(tradeName);
  const journalCard = page.locator('#tgit-trades tbody tr').filter({ has: page.getByText(tradeName, { exact: true }) }); await journalCard.getByRole('button', { name: 'Edit', exact: true }).click();
  assert.equal(await form.locator('textarea[name=notes]').inputValue(), 'Feeling calm; no financial effect.');
  assert.equal(await form.locator('input[name=planned_stop]').inputValue(), '0.123456789012345678');
  assert.equal(await page.locator('#tgit-confluence-items input').nth(0).isChecked(), true); assert.equal(await page.locator('#tgit-confluence-items input').nth(1).isChecked(), false);
  assert((await page.locator('#tgit-tags-labels').textContent()).includes('Café review'));
  await page.getByRole('tab', { name: 'Images', exact: true }).click(); assert.equal(await page.locator('#tgit-gallery tbody tr').count(), 3); assert.equal(await page.locator('#tgit-gallery tbody tr').filter({ has: page.getByText('UI-one.png', { exact: true }) }).locator('[data-label=Stage]').textContent(), 'entry'); assert.deepEqual(errors, []);
  await page.getByRole('tab', { name: 'Plan and journal', exact: true }).click(); await form.locator('textarea[name=notes]').fill('Unsaved navigation fixture');
  await page.getByRole('tab', { name: 'Summary', exact: true }).click();
  const rejectDiscard = (dialog) => dialog.dismiss(); page.on('dialog', rejectDiscard); await page.locator('#tgit-close-trade').click();
  assert.equal(await page.locator('#tgit-trade-detail').isVisible(), true); page.off('dialog', rejectDiscard);
  await page.getByRole('tab', { name: 'Plan and journal', exact: true }).click(); assert.equal(await form.locator('textarea[name=notes]').inputValue(), 'Unsaved navigation fixture');
  await form.locator('textarea[name=notes]').fill('Feeling calm; no financial effect.'); await page.locator('#tgit-close-trade').click();
  assert.equal(await page.getByRole('searchbox', { name: 'Search Trades', exact: true }).inputValue(), tradeName);
  assert.equal(await journalCard.locator('[data-label="Active images"]').textContent(), '3');
  console.log('CHECK Dirty cancellation and list context retained.');
  await journalCard.getByRole('button', { name: 'View', exact: true }).click(); await page.waitForFunction(() => !window.tgitWriteBusy);
  const deepLink = page.url(); await page.goBack(); await page.locator('#tgit-trade-list').waitFor({ state: 'visible' });
  assert.equal(await page.getByRole('searchbox', { name: 'Search Trades', exact: true }).inputValue(), tradeName);
  await page.goto(deepLink); await page.locator('#tgit-trade-detail').waitFor({ state: 'visible' }); await page.getByRole('tab', { name: 'Plan and journal', exact: true }).click();
  assert.equal(await form.locator('textarea[name=notes]').inputValue(), 'Feeling calm; no financial effect.'); assert.deepEqual(errors, []);
  await page.waitForFunction(() => !window.tgitWriteBusy);
  const concurrentStatus = await page.evaluate(async () => {
   const url = new URL(location.href), target = `workspaces/${url.searchParams.get('tgit_workspace')}/trades/${url.searchParams.get('tgit_trade')}`;
   const response = await fetch(tgitRestUrl(tgitConfig.root, target), { headers: { 'X-WP-Nonce': tgitConfig.nonce } }); const data = (await response.json()).data;
   const replacement = { title: data.trade.title, asset_id: Number(data.trade.asset_id), state: data.trade.state, opened_on: data.trade.opened_on || '', closed_on: data.trade.closed_on || '', strategy_version_id: Number(data.trade.strategy_version_id), transaction_ids: data.fills.map((fill) => Number(fill.id)), journal: { ...data.journal.fields, notes: 'Concurrent fixture revision' }, expected_revision: Number(data.trade.revision) };
   return (await fetch(tgitRestUrl(tgitConfig.root, target), { method: 'POST', headers: { 'X-WP-Nonce': tgitConfig.nonce, 'Idempotency-Key': crypto.randomUUID(), 'Content-Type': 'application/json' }, body: JSON.stringify(replacement) })).status;
  }); assert.equal(concurrentStatus, 200);
  await form.locator('textarea[name=notes]').fill('Retained conflict draft'); await page.locator('#tgit-save-journal').click();
  await page.getByRole('button', { name: 'Reload latest journal', exact: true }).waitFor({ state: 'visible' }); assert.equal(await form.locator('textarea[name=notes]').inputValue(), 'Retained conflict draft');
  page.once('dialog', (dialog) => dialog.accept()); await page.getByRole('button', { name: 'Reload latest journal', exact: true }).click(); await page.waitForFunction(() => !window.tgitWriteBusy);
  await page.getByRole('tab', { name: 'Plan and journal', exact: true }).click(); assert.equal(await form.locator('textarea[name=notes]').inputValue(), 'Concurrent fixture revision');
  assert.deepEqual(errors, []);
  console.log('PASS Desktop/mobile journal: minimal creation, table/detail tabs, snapshot, exact fields, three uploads, image actions, dirty guards, list context, Back and deep links.');
 } finally { await browser.close(); }
})().catch((error) => { console.error(error.stack); process.exitCode = 1; });
