/* Disposable manual watchlist, authored research and scenario browser workflow. */
'use strict';
const fs = require('node:fs');
const assert = require('node:assert/strict');
const { chromium } = require(process.env.TGIT_PLAYWRIGHT_MODULE || './browser/node_modules/playwright-core');
const fixture = JSON.parse(fs.readFileSync('tmp/journal-http-fixtures.json', 'utf8'));
const noteText = `Browser research thesis — Café 📈 ${Date.now()}`;
const revisedText = `Revised thesis — résumé 📈 ${Date.now()}`;
(async () => {
 const browser = await chromium.launch({ executablePath: process.env.TGIT_CHROME_EXECUTABLE || 'C:/Program Files/Google/Chrome/Application/chrome.exe', headless: true });
 try {
  const context = await browser.newContext({ viewport: { width: 1100, height: 900 } }); const session = fixture.sessions.owner;
  await context.addCookies([{ name: session.cookie_name, value: session.cookie_value, url: 'http://127.0.0.1:19308', httpOnly: true }]);
  const page = await context.newPage(); page.setDefaultTimeout(60000); const errors = []; page.on('pageerror', (error) => errors.push(error.message));
  await page.goto('http://127.0.0.1:19308/preview'); await page.locator('#tgit-workspace').selectOption(String(fixture.workspace));
  await page.locator('#tgit-content').waitFor({ state: 'visible' });
  if (await page.locator('.tgit-menu-toggle').isVisible() && await page.locator('.tgit-menu-toggle').getAttribute('aria-expanded') === 'false') await page.locator('.tgit-menu-toggle').click();
  await page.getByRole('tab', { name: 'Research', exact: true }).click();
  const name = 'Browser watchlist ' + Date.now(); const create = page.locator('#tgit-watchlist-form');
  await create.locator('input[name=name]').fill(name); await create.getByRole('button', { name: 'Create watchlist' }).click();
  const item = page.locator('#tgit-watchlist-item-form'); await item.locator('select[name=watchlist_id]').selectOption({ label: name });
  await item.locator('select[name=asset_id]').selectOption({ index: 0 });
  await item.locator('input[name=target_buy]').fill('90'); await item.locator('input[name=target_sell]').fill('120');
  await item.locator('textarea[name=thesis]').fill('User-authored target'); await item.locator('input[name=tags]').fill('manual, fixture');
  await item.getByRole('button', { name: 'Save watchlist item' }).click();
  await page.locator('#tgit-watchlist-items').getByText('90.00 / 120.00 USD').waitFor();
  await page.locator('#tgit-watchlist-items tbody tr').first().getByRole('button', { name: 'Edit' }).click();
  await item.locator('input[name=target_buy]').fill('85'); await item.getByRole('button', { name: 'Save watchlist item' }).click();
  await page.locator('#tgit-watchlist-items').getByText('85.00 / 120.00 USD').waitFor();
  const note = page.locator('#tgit-research-note-form'); await note.locator('select[name=asset_id]').selectOption({ index: 0 });
  await note.locator('textarea[name=content]').fill(noteText); await note.getByRole('button', { name: 'Save research note' }).click();
  await page.getByRole('searchbox', { name: 'Search Research notes', exact: true }).fill(noteText);
  await page.locator('#tgit-research-notes').getByText(noteText, { exact: true }).waitFor();
  await page.locator('#tgit-research-notes tbody tr').filter({ hasText: noteText }).getByRole('button', { name: 'Edit' }).click();
  assert.equal(await note.locator('textarea[name=content]').inputValue(), noteText);
  await note.locator('textarea[name=content]').fill(revisedText); await note.locator('input[name=reason]').fill('New facts');
  await note.getByRole('button', { name: 'Save research note' }).click(); await page.getByRole('searchbox', { name: 'Search Research notes', exact: true }).fill(revisedText);
  await page.locator('#tgit-research-notes').getByText(revisedText, { exact: true }).waitFor();
  await page.evaluate(() => scrollTo(0, 0));
  const inputHeight = await create.locator('input[name=name]').evaluate((input) => input.getBoundingClientRect().height); assert(inputHeight >= 40 && inputHeight <= 48);
  await page.screenshot({ path: 'tmp/ux-research-desktop.png', fullPage: true }); await page.setViewportSize({ width: 360, height: 800 });
  assert(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)); await page.screenshot({ path: 'tmp/ux-research-mobile.png', fullPage: true });
  await page.locator('#tgit-content').waitFor({ state: 'visible' });
  if (await page.locator('.tgit-menu-toggle').isVisible() && await page.locator('.tgit-menu-toggle').getAttribute('aria-expanded') === 'false') await page.locator('.tgit-menu-toggle').click();
  await page.getByRole('tab', { name: 'Calculators', exact: true }).click();
  await page.locator('#tgit-calculators-section details').evaluateAll((items) => items.forEach((item) => { item.open = true; }));
  const calc = page.locator('#tgit-crypto-calculator'); await calc.locator('input[name=buy_price]').fill('20'); await calc.locator('input[name=sell_price]').fill('30'); await calc.locator('input[name=investment]').fill('100');
  await calc.getByRole('button', { name: 'Calculate profit' }).click(); await page.locator('#tgit-crypto-result').getByText('Profit: 50.00 USD (50.00%)').waitFor();
  assert.deepEqual(errors, []);
  console.log('PASS Browser watchlist create/revise, research create/revise and private calculator; no JavaScript errors.');
 } finally { await browser.close(); }
})().catch((error) => { console.error(error.message); process.exitCode = 1; });
